/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/_timeline'
import { Route as TimelineIndexRouteImport } from './routes/_timeline/index'
import { Route as TimelineAssetChecksumRouteImport } from './routes/_timeline/asset.$checksum'

const TimelineRoute = TimelineRouteImport.update({
  id: '/_timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineIndexRoute = TimelineIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TimelineRoute,
} as any)
const TimelineAssetChecksumRoute = TimelineAssetChecksumRouteImport.update({
  id: '/asset/$checksum',
  path: '/asset/$checksum',
  getParentRoute: () => TimelineRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof TimelineIndexRoute
  '/asset/$checksum': typeof TimelineAssetChecksumRoute
}
export interface FileRoutesByTo {
  '/': typeof TimelineIndexRoute
  '/asset/$checksum': typeof TimelineAssetChecksumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_timeline': typeof TimelineRouteWithChildren
  '/_timeline/': typeof TimelineIndexRoute
  '/_timeline/asset/$checksum': typeof TimelineAssetChecksumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/asset/$checksum'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/asset/$checksum'
  id: '__root__' | '/_timeline' | '/_timeline/' | '/_timeline/asset/$checksum'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TimelineRoute: typeof TimelineRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_timeline': {
      id: '/_timeline'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_timeline/': {
      id: '/_timeline/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof TimelineIndexRouteImport
      parentRoute: typeof TimelineRoute
    }
    '/_timeline/asset/$checksum': {
      id: '/_timeline/asset/$checksum'
      path: '/asset/$checksum'
      fullPath: '/asset/$checksum'
      preLoaderRoute: typeof TimelineAssetChecksumRouteImport
      parentRoute: typeof TimelineRoute
    }
  }
}

interface TimelineRouteChildren {
  TimelineIndexRoute: typeof TimelineIndexRoute
  TimelineAssetChecksumRoute: typeof TimelineAssetChecksumRoute
}

const TimelineRouteChildren: TimelineRouteChildren = {
  TimelineIndexRoute: TimelineIndexRoute,
  TimelineAssetChecksumRoute: TimelineAssetChecksumRoute,
}

const TimelineRouteWithChildren = TimelineRoute._addFileChildren(
  TimelineRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  TimelineRoute: TimelineRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
